### ISSUE TITLE
Can i help :P

### ISSUE THREAD

**Issue by MNA4** [sonicx180/Replit-News#1]
can i help too? 😀 my replit account is banned but i still can code

**Comment by sonicx180** [comment]
umm, it's in nextjs but u can contribute with prs :)

**Comment by MNA4** [comment]
what is prs :P

**Comment by sonicx180** [comment]
pull request :P

**Comment by BusterSR** [comment]
I've been waiting for something like this to be created ever since ironcladdev stopped making blog posts i'll be willing to help as well
